# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [1]:
import pandas as pd
import numpy as np 
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

In [2]:
df.head(5)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [4]:
df.shape

(10910, 26)

In [5]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

In [7]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()                                        
        .str.replace(r"(?<!^)(?=[A-Z])", "_", regex=True)   
        .str.replace(r"[^\w]+", "_", regex=True)             
        .str.lower()                                         
        .str.replace(r"_+", "_", regex=True)                 
        .str.strip("_")                                      
    )
    return df
df = clean_columns(df)    
df.columns

Index(['unnamed_0', 'customer', 'state', 'customer_lifetime_value', 'response',
       'coverage', 'education', 'effective_to_date', 'employment_status',
       'gender', 'income', 'location_code', 'marital_status',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

In [8]:
df = df.drop(columns="unnamed_0")
df.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employment_status', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size', 'vehicle_type'],
      dtype='object')

In [9]:
df.head(1)

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.21696,No,Basic,College,2/18/11,Employed,M,48029,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.8,Four-Door Car,Medsize,NaN

In [9]:
#Create a new DataFrame that only includes customers who:
#have a low total_claim_amount (e.g., below $1,000),
#have a response "Yes" to the last marketing campaign.

In [12]:
low_claim = df["total_claim_amount"] < 1000
responded_yes = df["response"] == "Yes"

df_filtered = df[low_claim & responded_yes]

df_filtered.head(5)

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employment_status,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [13]:
df_filtered.shape

(1399, 25)

In [ ]:
#Using the original Dataframe, analyze:
#the average monthly_premium and/or customer lifetime value by policy_type and gender for customers who responded "Yes", and
#compare these insights to total_claim_amount patterns, and discuss which segments appear most profitable or low-risk for the company.

In [47]:
analysis = (
    df[df["response"] == "Yes"]          
    .groupby(["policy_type", "gender"])  
    .agg(
        avg_monthly_premium=("monthly_premium_auto", "mean"),
        avg_clv=("customer_lifetime_value", "mean"),
        avg_total_claim_amount=("total_claim_amount", "mean")
    )
    .round(2)  
)

analysis

                       avg_monthly_premium  avg_clv  avg_total_claim_amount
policy_type    gender
Corporate Auto F                     94.30  7712.63                  433.74
               M                     92.19  7944.47                  408.58
Personal Auto  F                     99.00  8339.79                  452.97
               M                     91.09  7448.38                  457.01
Special Auto   F                     92.31  7691.58                  453.28
               M                     86.34  8247.09                  429.53

Females of the policy Personal Auto have the highest avg_monthly_premium and the highest avg_customer_lifetime_value
But, it's the 3rd in avg_total_claim_amount, which is bad, but not so far from the average. 
All things considered it represents the most profitable or low-risk for the company.

In [ ]:
#Analyze the total number of customers who have policies in each state, 
#and then filter the results to only include states where there are more than 500 customers.

In [55]:
df["number_of_policies"].min()

1

In [57]:
customers_by_state = df["state"].value_counts()
customers_by_state

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

In [52]:
customers_over_500 = customers_by_state[customers_by_state > 500]
customers_over_500

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

In [ ]:
#Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [63]:
df.groupby(["education", "gender"])["customer_lifetime_value"].agg(["min","max","median"]).round(2)

                                 min       max   median
education            gender
Bachelor             F       1904.00  73225.96  5640.51
                     M       1898.01  67907.27  5548.03
College              F       1898.68  61850.19  5623.61
                     M       1918.12  61134.68  6005.85
Doctor               F       2395.57  44856.11  5332.46
                     M       2267.60  32677.34  5577.67
High School or Below F       2144.92  55277.45  6039.55
                     M       1940.98  83325.38  6286.73
Master               F       2417.78  51016.07  5729.86
                     M       2272.31  50568.26  5579.10

In [65]:
df.groupby(["education", "gender"])["customer_lifetime_value"].describe().round(2)

                              count     mean      std      min      25%  \
education            gender
Bachelor             F       1700.0  7874.27  6614.11  1904.00  4118.59
                     M       1572.0  7703.60  6658.46  1898.01  3842.35
College              F       1608.0  7748.82  6678.30  1898.68  3866.80
                     M       1596.0  8052.46  6716.96  1918.12  4035.90
Doctor               F        200.0  7328.51  6930.56  2395.57  3531.28
                     M        201.0  7415.33  5460.94  2267.60  3557.37
High School or Below F       1590.0  8675.22  7497.85  2144.92  4158.28
                     M       1556.0  8149.69  7190.62  1940.98  4197.68
Master               F        475.0  8157.05  6621.77  2417.78  4061.87
                     M        412.0  8168.83  7362.16  2272.31  3933.03

                                 50%      75%       max
education            gender
Bachelor             F       5640.51  8723.24  73225.96
                     M       5548.03  8646.70  67907.27
College              F       5623.61  8714.92  61850.19
                     M       6005.85  9157.76  61134.68
Doctor               F       5332.46  7662.70  44856.11
                     M       5577.67  8828.38  32677.34
High School or Below F       6039.55  9457.34  55277.45
                     M       6286.73  9002.19  83325.38
Master               F       5729.86  9264.04  51016.07
                     M       5579.10  9031.08  50568.26

The group that has the most outliers is High School or Below on Males

In [ ]:
#The marketing team wants to analyze the number of policies sold by state and month. 
#Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [76]:
df["effective_to_date"].dtype

dtype('O')

In [86]:
df["effective_to_date"] = pd.to_datetime(df["effective_to_date"], format="%m/%d/%y")
df["month"] = df["effective_to_date"].dt.month_name()

In [84]:
df["month"]

0        February
1         January
2        February
3         January
4         January
           ...
10905     January
10906     January
10907    February
10908    February
10909     January
Name: month, Length: 10910, dtype: object

In [82]:
policies_table = df.pivot_table(
    index="state",
    columns="month",
    values="number_of_policies",
    aggfunc="sum"
)

policies_table

month       February  January
state
Arizona         2864     3052
California      4929     5673
Nevada          1278     1493
Oregon          3969     4697
Washington      1225     1358

In [ ]:
#Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.
#Hint:

#To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. 
#Afterwards, you will need to sort the data by the count of policies sold in descending order.
#Next, you will select the top 3 states with the highest number of policies sold.
#Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.

In [92]:
total_policies_by_state = df.groupby("state")["number_of_policies"].sum().sort_values(ascending=False)
top_3_states = total_policies_by_state.head(3).index
top_states_df = df[df["state"].isin(top_3_states)]
policies_top3 = top_states_df.pivot_table(
    index="state",
    columns="month",
    values="number_of_policies",
    aggfunc="sum"
)
month_order = ["January", "February"]
existing_months = [m for m in month_order if m in policies_top3.columns]
policies_top3 = policies_top3.reindex(columns=existing_months)
policies_top3 = policies_top3.reindex(index=top_3_states)
policies_top3

month       January  February
state
California     5673      4929
Oregon         4697      3969
Arizona        3052      2864